# Collective
# ----------

# Define the Open Collective you want to link the repository with. Use the slug.

collective: <YOUR-COLLECTIVE-SLUG>

# Examples

# collective: webpack

# Invalid examples

# collective: https://opencollective.com/webpack
# collective: opencollective.com/webpack
# collective: https://opencollective.com/webpack/contribute/backer-266

# Invitation
# ----------

# Post a comment on issues created by non contributors.

invitation: >-
  Hey <author> :wave:,\n
  Thank you for opening an issue.
  We will get back to you as soon as we can.
  Also, check out our Open Collective and consider contributing financially.\n
  <link>\n
  > PS.: We offer `priority` support for all financial contributors.
  Don't forget to add `priority` label once you start contributing :smile:

# Tiers
# -----

# In this section you can define specific behavior for all supported tiers, ie: "backer" "and sponsor".

tiers:
  # # Uncomment this block if you want to activate a custom comment for people contributors to the "backer" tier
  # - tiers: ['backer']
  #   labels: ['priority']
  #   message: >-
  #     Hey <author> :wave:,\n
  #     Thank you for being a "backer"
  #     We will handle your issue with priority support.
  #     To make sure we don't forget how special you are, we added a `priority` label to your issue.\n
  #     Thank you again for contributing :tada:!

  # # Uncomment this block if you want to activate a custom comment for people contributors to the "sponsor" tier
  # - tiers: ['sponsor']
  #   labels: ['priority']
  #   message: >-
  #     Hey <author> :wave:,\n
  #     Thank you for being a "sponsor".
  #     We will handle your issue with priority support.
  #     To make sure we don't forget how special you are, we added a `priority` label to your issue.\n
  #     Thank you again for contributing :tada:!

  # This rule will be catching any contributor not already matched by other rules, whatever their tiers (also custom contributions)
  - tiers: '*'
    labels: ['priority']
    message: >
      Hey <author> :wave:,\n
      Thank you for contributing to our project financially.
      We will handle your issue with priority support.
      To make sure we don't forget how special you are, we added a `priority` label to your issue.\n
      Thank you again for contributing :tada:!
